"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.0.0-beta.1"
COMMIT = "2d4cbc3f08bfe8eb5ccfba32c9b3c33ba7717ff3"
MAJOR = 1
MINOR = 0
PATCH = 0
